<a href="https://colab.research.google.com/github/utkarsh-prakash/Google-Colab-Notebooks/blob/main/tensors_and_shapes_for_sequence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [ ]:
model = tf.keras.models.Sequential([
            tf.keras.layers.SimpleRNN(20, input_shape=[None, 1], return_sequences=True),
            tf.keras.layers.SimpleRNN(20),
            tf.keras.layers.Dense(1),
            tf.keras.layers.Lambda(lambda x: x*100.0)
])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, None, 20)          440       
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 20)                820       
_________________________________________________________________
dense (Dense)                (None, 1)                 21        
_________________________________________________________________
lambda (Lambda)              (None, 1)                 0         
Total params: 1,281
Trainable params: 1,281
Non-trainable params: 0
_________________________________________________________________


In [ ]:
import numpy as np
x = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
x = tf.convert_to_tensor(x)
x = tf.expand_dims(x, axis=-1)
y = np.array([[5],[9], [13]])

In [ ]:
model.compile(optimizer='adam', loss='mse')
model.fit(x=x, y=y, epochs=100, verbose=0)

In [ ]:
model.predict(np.array([[[13],[14],[15],[16]]]))

array([[15.616205]], dtype=float32)

In [ ]:
x = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
x = tf.convert_to_tensor(x)
x

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])>

In [ ]:
x = tf.expand_dims(x, axis=-1)
x

<tf.Tensor: shape=(3, 4, 1), dtype=int64, numpy=
array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])>

In [ ]:
model.predict(x)

array([[ 4.7565546],
       [ 8.809564 ],
       [12.769097 ]], dtype=float32)